#!/usr/bin/env python
# coding: utf-8

from setuptools import setup

setup(
    name="viralata",
    version='0.1',
    description='Microservice for Authentication: Restlike & Social.',
    author='Andrés M. R. Martano',
    author_email='andres@inventati.org',
    url='https://gitlab.com/ok-br/viralata',
    packages=["viralata"],
    install_requires=[
        # Main deps:
        # 'Flask',
        # 'Flask-Script',
        # 'Flask-Restplus',
        # 'Flask-CORS',
        # 'Flask-Mail',
        # 'Flask-SQLAlchemy',
        # 'python-social-auth',
        # 'passlib',
        # 'viratoken',
        # 'bleach',
        # 'sqlalchemy-utils',
        # 'arrow',
        # 'psycopg2',  # for Postgres support
        'aniso8601==1.0.0',
        'arrow==0.7.0',
        'bleach==1.4.2',
        'blinker==1.4',
        'cffi==1.2.1',
        'cryptography==1.0.2',
        'decorator==4.0.4',
        'enum34==1.0.4',
        'Flask==0.10.1',
        'Flask-Cors==2.1.0',
        'Flask-Mail==0.9.1',
        'Flask-RESTful==0.3.4',
        'flask-restplus==0.8.0',
        'Flask-Script==2.0.5',
        'Flask-SQLAlchemy==2.0',
        'functools32==3.2.3.post2',
        'html5lib==1.0b8',
        'idna==2.0',
        'ipaddress==1.0.14',
        'ipython==4.0.0',
        'ipython-genutils==0.1.0',
        'itsdangerous==0.24',
        'Jinja2==2.8',
        'jsonschema==2.5.1',
        'MarkupSafe==0.23',
        'oauthlib==1.0.3',
        'passlib==1.6.5',
        'path.py==8.1.2',
        'pexpect==4.0.1',
        'pickleshare==0.5',
        'psycopg2==2.6.1',
        'ptyprocess==0.5',
        'pyasn1==0.1.9',
        'pycparser==2.14',
        'PyJWT==1.4.0',
        'python-dateutil==2.4.2',
        'python-openid==2.2.5',
        'python-social-auth==0.2.13',
        'pytz==2015.6',
        'requests==2.8.1',
        'requests-oauthlib==0.5.0',
        'simplegeneric==0.8.1',
        'six==1.10.0',
        'SQLAlchemy==1.0.8',
        'SQLAlchemy-Utils==0.31.0',
        'traitlets==4.0.0',
        'viratoken',
        'Werkzeug==0.10.4',
        'wheel==0.24.0',
    ],
    keywords=['authentication', 'microservice'],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Environment :: Web Environment",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 2",
        "Programming Language :: Python :: 3",
        "Environment :: Web Environment",
        "Topic :: Internet :: WWW/HTTP",
        "Topic :: Internet :: WWW/HTTP :: Session",
    ]
)
