#!/bin/sh

# https://github.com/bilderbuchi/tiny_tiny_rss-openshift-quickstart/commit/4a8318be6df40cc48bfab62b2a198a20458ef4a5
# Daily manual full-vacuum of the database to work around an Openshift bug
# causing autovacuum not to work. 
# See https://bugzilla.redhat.com/show_bug.cgi?id=849428 which is a duplicate
# of the non-accessible https://bugzilla.redhat.com/show_bug.cgi?id=806016
echo "Vacuuming database..."
vacuumdb -f --host=$OPENSHIFT_POSTGRESQL_DB_HOST --port=$OPENSHIFT_POSTGRESQL_DB_PORT
returnvalue=$?
echo "Vacuuming ended"

exit $returnvalue

